@echo off
title Fennec Freelance, Serveur Express
echo ...
echo  === Lancement de l'application Employeur/Freelancer de Fennec Freelance en cours! ===
echo ...
echo ======================================================================================
echo                       Pour arreter le serveur, utilisez Ctrl+C
echo ======================================================================================
echo ...

npm start